import type { IntegrationMeta } from "./base"

export const INTEGRATION_REGISTRY: Record<string, IntegrationMeta> = {
  google: {
    id: "google",
    displayName: "Google Workspace",
    description: "Gmail, Google Calendar, and Google Drive — send emails, sync deadlines, manage documents.",
    logoEmoji: "🔵",
    category: "productivity",
    authType: "oauth",
    tier: 1,
    capabilities: ["send_email", "read_email", "create_calendar_event", "read_calendar", "upload_drive"],
  },
  clio: {
    id: "clio",
    displayName: "Clio",
    description: "Legal practice management — sync matters, contacts, time entries, and billing.",
    logoEmoji: "⚖️",
    category: "practice_management",
    authType: "oauth",
    tier: 1,
    capabilities: ["read_matter", "write_time_entry"],
    docsUrl: "https://app.clio.com/api/v4/documentation",
  },
  lawpay: {
    id: "lawpay",
    displayName: "LawPay",
    description: "Attorney-specific payment processing with IOLTA trust accounting compliance. Required for retainers.",
    logoEmoji: "💳",
    category: "payments",
    authType: "api_key",
    tier: 1,
    capabilities: ["process_payment", "create_invoice"],
    docsUrl: "https://developer.affinipay.com/",
  },
  stripe: {
    id: "stripe",
    displayName: "Stripe",
    description: "Flat-fee invoices and SaaS subscription billing. Use LawPay for trust accounting.",
    logoEmoji: "💜",
    category: "payments",
    authType: "api_key",
    tier: 1,
    capabilities: ["create_invoice", "process_payment"],
  },
  docusign: {
    id: "docusign",
    displayName: "DocuSign",
    description: "E-signatures on engagement letters, contracts, and settlement agreements.",
    logoEmoji: "✍️",
    category: "esignature",
    authType: "oauth",
    tier: 1,
    capabilities: ["send_for_signature"],
  },
  hubspot: {
    id: "hubspot",
    displayName: "HubSpot",
    description: "Pre-engagement CRM — leads, referrals, marketing pipeline, and deal tracking.",
    logoEmoji: "🟠",
    category: "marketing",
    authType: "oauth",
    tier: 2,
    capabilities: ["create_lead"],
  },
  notion: {
    id: "notion",
    displayName: "Notion",
    description: "Sync Notion pages as agent skill files — write in Notion, agents read it automatically.",
    logoEmoji: "⬜",
    category: "knowledge",
    authType: "api_key",
    tier: 2,
    capabilities: [],
  },
  quickbooks: {
    id: "quickbooks",
    displayName: "QuickBooks",
    description: "Sync invoices and payments to your accounting software.",
    logoEmoji: "📊",
    category: "accounting",
    authType: "oauth",
    tier: 2,
    capabilities: ["sync_accounting"],
  },
  calendly: {
    id: "calendly",
    displayName: "Calendly",
    description: "Client consultation scheduling — intake agent can create booking links.",
    logoEmoji: "📅",
    category: "scheduling",
    authType: "api_key",
    tier: 2,
    capabilities: ["book_consultation"],
  },
  square: {
    id: "square",
    displayName: "Square",
    description: "In-person payments and card reader for office consultations.",
    logoEmoji: "⬛",
    category: "payments",
    authType: "api_key",
    tier: 3,
    capabilities: ["process_payment"],
  },
  casetext: {
    id: "casetext",
    displayName: "Casetext / CoCounsel",
    description: "AI-powered legal research database — cheaper than Westlaw.",
    logoEmoji: "📚",
    category: "legal_research",
    authType: "api_key",
    tier: 3,
    capabilities: ["search_case_law"],
  },
  pacer: {
    id: "pacer",
    displayName: "PACER",
    description: "Federal court docket lookup and e-filing.",
    logoEmoji: "🏛️",
    category: "court_filing",
    authType: "api_key",
    tier: 3,
    capabilities: ["file_court_document", "search_case_law"],
  },
  pandadoc: {
    id: "pandadoc",
    displayName: "PandaDoc",
    description: "Alternative e-signature + proposal templates.",
    logoEmoji: "🐼",
    category: "esignature",
    authType: "api_key",
    tier: 3,
    capabilities: ["send_for_signature"],
  },
  slack: {
    id: "slack",
    displayName: "Slack",
    description: "Team notifications when your firm grows.",
    logoEmoji: "💬",
    category: "communication",
    authType: "oauth",
    tier: 3,
    capabilities: ["send_notification"],
  },
  zapier: {
    id: "zapier",
    displayName: "Zapier Webhook",
    description: "Connect any service not natively supported via Zapier automation.",
    logoEmoji: "⚡",
    category: "automation",
    authType: "api_key",
    tier: 3,
    capabilities: ["trigger_webhook"],
  },
}

export function getIntegrationsByTier(tier: 1 | 2 | 3): IntegrationMeta[] {
  return Object.values(INTEGRATION_REGISTRY).filter((i) => i.tier === tier)
}

export function getIntegrationsByCategory(category: string): IntegrationMeta[] {
  return Object.values(INTEGRATION_REGISTRY).filter((i) => i.category === category)
}
